### ISSUE TITLE
 Failed to download file (open_clip_pytorch_model.bin) for laion/CLIP-ViT-H-14-laion2B-s32B-b79K. 

### ISSUE THREAD

**Issue by 30410B** [donydchen/mvsplat360#10]
Thanks for your extraordinary work! When i try to reproduce your work， I find i can't conneted to url, how can i install this locally

**Comment by lingdoudoulingling** [comment]
Modify line 595-599 in the library file `/your_path/lib/python3.11/site-packages/sgm/modules/encoders/modules.py` to `pretrained="your_local_path"`.
line595
`model, _, _ = open_clip.create_model_and_transforms(
            arch,
            device=torch.device(default(init_device, "cpu")),
            pretrained="/your_local_path/CLIP-ViT-H-14-laion2B-s32B-b79K/open_clip_pytorch_model.bin",
        )`
You can refer to
[https://github.com/mlfoundations/open_clip](url)

**Comment by 30410B** [comment]
> Modify line 595-599 in the library file `/your_path/lib/python3.11/site-packages/sgm/modules/encoders/modules.py` to `pretrained="your_local_path"`. line595 `model, _, _ = open_clip.create_model_and_transforms( arch, device=torch.device(default(init_device, "cpu")), pretrained="/your_local_path/CLIP-ViT-H-14-laion2B-s32B-b79K/open_clip_pytorch_model.bin", )` You can refer to [https://github.com/mlfoundations/open_clip](url)

Thank you for your reply, i have addressed this issue by adding this file to my /root/.cache/huggingface/hub/models--laion--CLIP-ViT-H-14-laion2B-s32B-b79K, then it can be loaded.
