### ISSUE TITLE
About the training memory

### ISSUE THREAD

**Issue by zyqz97** [donydchen/mvsplat360#15]
Thanks for the great job!

I would like to inquire about memory usage for this project. When I run training on two A100 with 81920MB mem, it always gets Out of Memory after several steps of training, which contradicts with “#train mvsplat360; requires at least 80G VRAM” in ReadME. Is there something wrong?

here are my scripts (following the ReadME):
` export CUDA_VISIBLE_DEVICES=0,1  python -m src.main +experiment=dl3dv_mvsplat360  dataset.roots=[datasets/dl3dv]
`

**Comment by donydchen** [comment]
Hi @zyqz97, thanks for your appreciation.

The default setting should be able to fit into an 80G A100 GPU, which was also the GPU used to train our released model.

Did you encounter an error like `reserved memory is >> allocated memory`? If so, you might consider setting `export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True` to resolve the issue. 

If the above solution does not help, you might consider reducing the memory consumption of the encoder by following [this comment](https://github.com/donydchen/mvsplat/issues/78#issuecomment-2492591632).

**Comment by zyqz97** [comment]
Thank you for your prompt reply！ I have tried "export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True" before. Maybe there is something wrong with my machine. I will try the solution later!

**Comment by Selena1105** [comment]
Hi ! @zyqz97 
I've encountered the same problem. Did you find any solution to solve it ? Thank you!
