### ISSUE TITLE
Inquiry on checkpoints

### ISSUE THREAD

**Issue by YaoXingbo** [donydchen/mvsplat360#2]
作者您好，您的工作很棒，但是我有以下疑问
在自己train时候，我只需要下载其中一个checkpoints吗？还是两个都需要下载？
"Download the encoder pretrained weight from [MVSplat](https://github.com/donydchen/mvsplat) and save it to checkpoints/re10k.ckpt.
Download SVD pretrained weight from [generative-models](https://huggingface.co/stabilityai/stable-video-diffusion-img2vid/tree/main) and save it to checkpoints/svd.safetensors"

另外，发现了一处问题，通过检查代码发现，checkpoints应该保存到outputs/，而不是checkpoints/ ？

**Comment by donydchen** [comment]
Hi @YaoXingbo, thanks for your appreciation.

The two checkpoints are required when you plan to retrain the model "from scratch". More details are provided below.

* The `checkpoints/re10k.ckpt` is _optional_. It aims to provide a good initialisation for the feed-forward 3DGS module (i.e., the MVSplat backbone module), using weights pre-trained on RE10K. It is called at [encoder_costvolume.py](https://github.com/donydchen/mvsplat360/blob/main/src/model/encoder/encoder_costvolume.py#L150), and its path can be set at [dl3dv_mvsplat360.yaml](https://github.com/donydchen/mvsplat360/blob/main/config/experiment/dl3dv_mvsplat360.yaml#L97).

* The `checkpoints/svd.safetensors` is a _must_. It aims to initialise the diffusion module (i.e., the SVD refiner module) with _prior knowledge_ learned from the initial image-to-video task. It is called at  [svd_diffuser.py](https://github.com/donydchen/mvsplat360/blob/main/src/model/refiner/svd_diffuser.py#L83), and its path can be set at [svd_wo_mb_fps.yaml](https://github.com/donydchen/mvsplat360/blob/main/config/model/refiner/svd_wo_mb_fps.yaml#L3)

Alternatively, you can also _fine-tune_ using our released weights trained on DL3DV-10K, as detailed in the [README](https://github.com/donydchen/mvsplat360?tab=readme-ov-file#training). 

The "checkpoints" folder aims to store our pre-trained or released weights, while the "outputs" folder stores those training logs, including the checkpoints created during your own training.
