### ISSUE TITLE
Inquiry on evaluation

### ISSUE THREAD

**Issue by Dubhe-forever** [donydchen/mvsplat360#5]
Thanks for your great work! 

Recently When I prepared dl3dv according to the project workflow, I found that I couldn't perform evaluation (it would stop at **Testing: | | 0/? [00:00<?, ?it/s]**). However, when I used dl3dv_tiny, it worked pretty well. 

Also when I evaluate using the **_re10k_subset_** provided by _**pixelsplat**_ (https://drive.google.com/drive/folders/1joiezNCyQK2BvWMnfwHJpm2V77c7iYGe), it also stops at **Testing: | | 0/? [00:00<?, ?it/s]**. I checked and found that the dataset format is correct. I would like to humbly ask where the error might have occurred.

I would appreciate a lot if you could provide a detailed process for converting dl3dv, or how to check whether the converted torch chunk is valid? Looking forward to your reply, it is very very important to me.

**Comment by donydchen** [comment]
Hey @Dubhe-forever, thanks for your appreciation.

You might refer to my answers in #4 for potential solutions. I will also find time to double-check the processed codes shortly. Cheers.

**Comment by Dubhe-forever** [comment]
> Hey @Dubhe-forever, thanks for your appreciation.
> 
> You might refer to my answers in #4 for potential solutions. I will also find time to double-check the processed codes shortly. Cheers.

@donydchen Thanks a lot for your reply! It works！ : )
