### ISSUE TITLE
Wrong rendering result in folder outputs/test/dl3dv_480P_ctx5_tgt56/ImagesGSplat

### ISSUE THREAD

**Issue by RenieWell** [donydchen/mvsplat360#6]
After install the render in https://github.com/Chrixtar/latent-gaussian-rasterization.git, I got zero error. But when I try to run the dl3dv_480P_ctx5_tgt56 data, I still got the bad rendering result in ImagesGSplat folder, which looks like this:
![image](https://github.com/user-attachments/assets/8c155489-645a-4ae1-9c6f-03e2a01ccd0a)
after a few iterations, it looks like this:
![image](https://github.com/user-attachments/assets/e52db6fa-e222-4586-a6b3-21cb093db2a0)
and finally it will turn into totally white.

Is this normal?

**Comment by donydchen** [comment]
Hi @RenieWell, this is not normal. By loading the released pre-trained weight, the model should render novel views similar to the demo videos.

You might want to try manually install the 3DGS renderer via

```bash
git clone --recursive https://github.com/Chrixtar/latent-gaussian-rasterization.git
cd latent-gaussian-rasterization
pip install .
```

Hope it helps, cheers.

**Comment by RenieWell** [comment]
It works！
It is some problems with the install of latent-gaussian-rasterization.
Thanks for giving helps.
